from fileinput import filename
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, reply_keyboard
from aiogram.types.inline_keyboard import InlineKeyboardButton, InlineKeyboardMarkup
    

inlineButton1 = InlineKeyboardButton('Меню #1', callback_data='inlineButton1')
inlineButton2 = InlineKeyboardButton('Меню #2', callback_data='inlineButton2')
inlineButton3 = InlineKeyboardButton('Меню #3', callback_data='inlineButton3')
inlineButton4 = InlineKeyboardButton('Меню #4', callback_data='inlineButton4')
inlineButton5 = InlineKeyboardButton('Меню #5', callback_data='inlineButton5')
inlineButton6 = InlineKeyboardButton('Меню #6', callback_data='inlineButton6')
inlineButton7 = InlineKeyboardButton('Меню #7', callback_data='inlineButton7')
inlineButton8 = InlineKeyboardButton('Меню #8', callback_data='inlineButton8')

chooseButtons1 = InlineKeyboardMarkup(row_width=4).insert(inlineButton1).insert(inlineButton2).insert(inlineButton3).insert(inlineButton4).insert(inlineButton5).insert(inlineButton6).insert(inlineButton7).insert(inlineButton8)

#блок выбора продукции
inlineButton11 = InlineKeyboardButton('Морозильні скрині', callback_data='inlineButton11')
inlineButton12 = InlineKeyboardButton('Холодильні вітрини', callback_data='inlineButton12')
inlineButton13 = InlineKeyboardButton('Морозильні скрині для вагового морозива', callback_data='inlineButton13')
inlineButton14 = InlineKeyboardButton('Кондитерські холодильні вітрини', callback_data='inlineButton14')
inlineButton15 = InlineKeyboardButton('Шафи', callback_data='inlineButton15')
inlineButton16 = InlineKeyboardButton('Торговельне обладнання', callback_data='inlineButton16')
inlineButton17 = InlineKeyboardButton('Комплектуючі', callback_data='inlineButton17')
inlineButton18 = InlineKeyboardButton('Обладнання зі знижкою', callback_data='inlineButton18')
inlineButton19 = InlineKeyboardButton('Морозильні скрині з гнутим склом "прикасові"', callback_data='inlineButton9')
inlineButton20 = InlineKeyboardButton('Cкрині з гнутим склом серії S', callback_data='inlineButton10')
inlineButton21 = InlineKeyboardButton('Морозильні скрині з гнутим склом серії SF', callback_data='inlineButton11')
inlineButton22 = InlineKeyboardButton('Морозильні скрині з прямим склом', callback_data='inlineButton12')
inlineButton23 = InlineKeyboardButton('Морозильні скрині з глухою кришкою', callback_data='inlineButton13')
inlineButton24 = InlineKeyboardButton('Морозильні скрині - бонетного типу', callback_data='inlineButton14')
inlineButton25 = InlineKeyboardButton('Холодильна вітрина серії VGL (+2 ÷ +8°C)', callback_data='inlineButton15')
inlineButton26 = InlineKeyboardButton('Холодильна вітрина серії SGL (-2 ÷ +8°C)', callback_data='inlineButton16')
inlineButton27 = InlineKeyboardButton('Холодильна вітрина серії FGL (-2 ÷ +8°C)', callback_data='inlineButton17')
inlineButton28 = InlineKeyboardButton('Холодильна вітрина серії FGL (РЕСТАЙЛІНГ) (-2 ÷ +8°C)', callback_data='inlineButton18')
inlineButton29 = InlineKeyboardButton('Холодильна вітрина серії FDI (0 ÷ +8°C)', callback_data='inlineButton29')
inlineButton30 = InlineKeyboardButton('Морозильні скрині для вагового морозива серії SL', callback_data='inlineButton30')
inlineButton31 = InlineKeyboardButton('Морозильні скрині для вагового морозива серії Q', callback_data='inlineButton31')
inlineButton32 = InlineKeyboardButton('Шафи зі скляними дверима', callback_data='inlineButton32')
inlineButton33 = InlineKeyboardButton('Шафи з глухими дверима', callback_data='inlineButton33')
inlineButton34 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M100V', callback_data='inlineButton34')
inlineButton35 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M200V', callback_data='inlineButton35')
inlineButton36 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M200S', callback_data='inlineButton36')
inlineButton37 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M300S', callback_data='inlineButton37')
inlineButton38 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M300SH', callback_data='inlineButton38')
inlineButton39 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M400S', callback_data='inlineButton39')
inlineButton40 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M400SH', callback_data='inlineButton40')
inlineButton41 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M500S', callback_data='inlineButton41')
inlineButton42 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M600S', callback_data='inlineButton42')
inlineButton43 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA N600S', callback_data='inlineButton43')
inlineButton44 = InlineKeyboardButton('Середньотемпературна скриня з гнутим склом JUKA N300S', callback_data='inlineButton44')
inlineButton45 = InlineKeyboardButton('Середньотемпературна скриня з гнутим склом JUKA N200S', callback_data='inlineButton45')
inlineButton46 = InlineKeyboardButton('Середньотемпературна скриня з гнутим склом JUKA N400S', callback_data='inlineButton46')
inlineButton47 = InlineKeyboardButton('Середньотемпературна скриня з гнутим склом JUKA N500S', callback_data='inlineButton47')
inlineButton48 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M200SF', callback_data='inlineButton48')
inlineButton49 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M300SF', callback_data='inlineButton49')
inlineButton50 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M400SF', callback_data='inlineButton50')
inlineButton51 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M500SF', callback_data='inlineButton51')
inlineButton52 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M600SF', callback_data='inlineButton52')
inlineButton53 = InlineKeyboardButton('Морозильна скриня з гнутим склом JUKA M700SF', callback_data='inlineButton53')
inlineButton54 = InlineKeyboardButton('Морозильна скриня з прямим склом JUKA M200P', callback_data='inlineButton54')
inlineButton55 = InlineKeyboardButton('Морозильна скриня з прямим склом JUKA M300P', callback_data='inlineButton55')
inlineButton56 = InlineKeyboardButton('Морозильна скриня з прямим склом JUKA M400P', callback_data='inlineButton56')
inlineButton57 = InlineKeyboardButton('Морозильна скриня з прямим склом JUKA M500P', callback_data='inlineButton57')
inlineButton58 = InlineKeyboardButton('Морозильна скриня з прямим склом JUKA M600P', callback_data='inlineButton58')
inlineButton59 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M200Z', callback_data='inlineButton59')
inlineButton60 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M300Z', callback_data='inlineButton60')
inlineButton61 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M400Z', callback_data='inlineButton61')
inlineButton62 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M500Z', callback_data='inlineButton62')
inlineButton63 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M600Z', callback_data='inlineButton63')
inlineButton64 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M800Z', callback_data='inlineButton64')
inlineButton65 = InlineKeyboardButton('Морозильна скриня з глухою кришкою JUKA M1000Z', callback_data='inlineButton65')
inlineButton66 = InlineKeyboardButton('Середньотемпературна скриня бонетного типу JUKA N800S', callback_data='inlineButton66')
inlineButton67 = InlineKeyboardButton('Середньотемпературна скриня бонетного типу JUKA N800D', callback_data='inlineButton67')
inlineButton68 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA N800W', callback_data='inlineButton68')
inlineButton69 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M800W', callback_data='inlineButton69')
inlineButton70 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M800S', callback_data='inlineButton70')
inlineButton71 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M800D', callback_data='inlineButton71')
inlineButton72 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M1000V', callback_data='inlineButton72')
inlineButton73 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M1000S (-14...-23 °C)', callback_data='inlineButton73')
inlineButton74 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M1000S (-14...-23 °C ÷ +5...-5°C)', callback_data='inlineButton74')
inlineButton75 = InlineKeyboardButton('Морозильна скриня бонетного типу JUKA M1000S (+5...-5°C)', callback_data='inlineButton75')
inlineButton76 = InlineKeyboardButton('Холодильна вітрина VGL 130', callback_data='inlineButton76')
inlineButton77 = InlineKeyboardButton('Холодильна вітрина VGL 130 А', callback_data='inlineButton77')
inlineButton78 = InlineKeyboardButton('Холодильна вітрина VGL 160', callback_data='inlineButton78')
inlineButton79 = InlineKeyboardButton('Холодильна вітрина VGL 160 A', callback_data='inlineButton79')
inlineButton80 = InlineKeyboardButton('Холодильна вітрина VGL 190', callback_data='inlineButton80')
inlineButton81 = InlineKeyboardButton('Холодильна вітрина VGL 190 A', callback_data='inlineButton81')
inlineButton82 = InlineKeyboardButton('Холодильна вітрина SGL 130', callback_data='inlineButton82')
inlineButton83 = InlineKeyboardButton('Холодильна вітрина SGL 130 A', callback_data='inlineButton83')
inlineButton84 = InlineKeyboardButton('Холодильна вітрина SGL 160', callback_data='inlineButton84')
inlineButton85 = InlineKeyboardButton('Холодильна вітрина SGL 160 A', callback_data='inlineButton85')
inlineButton86 = InlineKeyboardButton('Холодильна вітрина SGL 190', callback_data='inlineButton86')
inlineButton87 = InlineKeyboardButton('Холодильна вітрина SGL 190 A', callback_data='inlineButton87')
inlineButton88 = InlineKeyboardButton('Холодильна вітрина SGL 260', callback_data='inlineButton88')
inlineButton89 = InlineKeyboardButton('Холодильна вітрина SGL 260A', callback_data='inlineButton89')
inlineButton90 = InlineKeyboardButton('Холодильна вітрина FGL 130', callback_data='inlineButton90')
inlineButton91 = InlineKeyboardButton('Холодильна вітрина FGL 130 A', callback_data='inlineButton91')
inlineButton92 = InlineKeyboardButton('Холодильна вітрина FGL 160', callback_data='inlineButton92')
inlineButton93 = InlineKeyboardButton('Холодильна вітрина FGL 160 A', callback_data='inlineButton93')
inlineButton94 = InlineKeyboardButton('Холодильна вітрина FGL 190', callback_data='inlineButton94')
inlineButton95 = InlineKeyboardButton('Холодильна вітрина FGL 190 A', callback_data='inlineButton95')
inlineButton96 = InlineKeyboardButton('Холодильна вітрина FGL 260А (Restyling)', callback_data='inlineButton96')
inlineButton97 = InlineKeyboardButton('Холодильна вітрина FGL 130 (Restyling)', callback_data='inlineButton97')
inlineButton98 = InlineKeyboardButton('Холодильна вітрина FGL 130 A (Restyling)', callback_data='inlineButton98')
inlineButton99 = InlineKeyboardButton('Холодильна вітрина FGL 160 (Restyling)', callback_data='inlineButton99')
inlineButton100 = InlineKeyboardButton('Холодильна вітрина FGL 160 A (Restyling)', callback_data='inlineButton100')
inlineButton101 = InlineKeyboardButton('Холодильна вітрина FGL 190 (Restyling)', callback_data='inlineButton101')
inlineButton102 = InlineKeyboardButton('Холодильна вітрина FGL 190 A (Restyling)', callback_data='inlineButton102')
inlineButton103 = InlineKeyboardButton('Холодильна вітрина FGL 260 (Restyling)', callback_data='inlineButton103')
inlineButton104 = InlineKeyboardButton('Кутовий модуль FDI E', callback_data='inlineButton104')
inlineButton105 = InlineKeyboardButton('Холодильна вітрина FDI 160 A', callback_data='inlineButton105')
inlineButton106 = InlineKeyboardButton('Холодильна вітрина FDI 197 A', callback_data='inlineButton106')
inlineButton107 = InlineKeyboardButton('Холодильна вітрина FDI 260 A', callback_data='inlineButton107')
inlineButton108 = InlineKeyboardButton('Морозильна скриня для продажу вагового морозива JUKA M300SL', callback_data='inlineButton108')
inlineButton109 = InlineKeyboardButton('Морозильна скриня для продажу вагового морозива JUKA M400SL', callback_data='inlineButton109')
inlineButton110 = InlineKeyboardButton('Морозильна скриня для продажу вагового морозива JUKA M600SL', callback_data='inlineButton110')



chooseInlineButtons1 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons1.insert(inlineButton11)
chooseInlineButtons1.insert(inlineButton12)
chooseInlineButtons1.insert(inlineButton13)
chooseInlineButtons1.insert(inlineButton14)
chooseInlineButtons1.insert(inlineButton15)
chooseInlineButtons1.insert(inlineButton16)
chooseInlineButtons1.insert(inlineButton17)
chooseInlineButtons1.insert(inlineButton18)

chooseInlineButtons2 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons2.insert(inlineButton19)
chooseInlineButtons2.insert(inlineButton20)
chooseInlineButtons2.insert(inlineButton21)
chooseInlineButtons2.insert(inlineButton22)
chooseInlineButtons2.insert(inlineButton23)
chooseInlineButtons2.insert(inlineButton24)

chooseInlineButtons3 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons3.insert(inlineButton25)
chooseInlineButtons3.insert(inlineButton26)
chooseInlineButtons3.insert(inlineButton27)
chooseInlineButtons3.insert(inlineButton28)
chooseInlineButtons3.insert(inlineButton29)

chooseInlineButtons4 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons4.insert(inlineButton30)
chooseInlineButtons4.insert(inlineButton31)

chooseInlineButtons5 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons5.insert(inlineButton32)
chooseInlineButtons5.insert(inlineButton33)

chooseInlineButtons6 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons6.insert(inlineButton34)
chooseInlineButtons6.insert(inlineButton35)

chooseInlineButtons7 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons7.insert(inlineButton36)
chooseInlineButtons7.insert(inlineButton37)
chooseInlineButtons7.insert(inlineButton38)
chooseInlineButtons7.insert(inlineButton39)
chooseInlineButtons7.insert(inlineButton40)
chooseInlineButtons7.insert(inlineButton41)
chooseInlineButtons7.insert(inlineButton42)
chooseInlineButtons7.insert(inlineButton43)
chooseInlineButtons7.insert(inlineButton44)
chooseInlineButtons7.insert(inlineButton45)
chooseInlineButtons7.insert(inlineButton46)
chooseInlineButtons7.insert(inlineButton47)

chooseInlineButtons8 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons8.insert(inlineButton48)
chooseInlineButtons8.insert(inlineButton49)
chooseInlineButtons8.insert(inlineButton50)
chooseInlineButtons8.insert(inlineButton51)
chooseInlineButtons8.insert(inlineButton52)
chooseInlineButtons8.insert(inlineButton53)

chooseInlineButtons9 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons9.insert(inlineButton54)
chooseInlineButtons9.insert(inlineButton55)
chooseInlineButtons9.insert(inlineButton56)
chooseInlineButtons9.insert(inlineButton57)
chooseInlineButtons9.insert(inlineButton58)

chooseInlineButtons10 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons10.insert(inlineButton59)
chooseInlineButtons10.insert(inlineButton60)
chooseInlineButtons10.insert(inlineButton61)
chooseInlineButtons10.insert(inlineButton62)
chooseInlineButtons10.insert(inlineButton63)
chooseInlineButtons10.insert(inlineButton64)
chooseInlineButtons10.insert(inlineButton65)

chooseInlineButtons11 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons11.insert(inlineButton66)
chooseInlineButtons11.insert(inlineButton67)
chooseInlineButtons11.insert(inlineButton68)
chooseInlineButtons11.insert(inlineButton69)
chooseInlineButtons11.insert(inlineButton70)
chooseInlineButtons11.insert(inlineButton71)
chooseInlineButtons11.insert(inlineButton72)
chooseInlineButtons11.insert(inlineButton73)
chooseInlineButtons11.insert(inlineButton74)
chooseInlineButtons11.insert(inlineButton75)

chooseInlineButtons12 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons12.insert(inlineButton76)
chooseInlineButtons12.insert(inlineButton77)
chooseInlineButtons12.insert(inlineButton78)
chooseInlineButtons12.insert(inlineButton79)
chooseInlineButtons12.insert(inlineButton80)
chooseInlineButtons12.insert(inlineButton81)

chooseInlineButtons13 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons13.insert(inlineButton82)
chooseInlineButtons13.insert(inlineButton83)
chooseInlineButtons13.insert(inlineButton84)
chooseInlineButtons13.insert(inlineButton85)
chooseInlineButtons13.insert(inlineButton86)
chooseInlineButtons13.insert(inlineButton87)
chooseInlineButtons13.insert(inlineButton88)
chooseInlineButtons13.insert(inlineButton89)

chooseInlineButtons14 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons14.insert(inlineButton90)
chooseInlineButtons14.insert(inlineButton91)
chooseInlineButtons14.insert(inlineButton92)
chooseInlineButtons14.insert(inlineButton93)
chooseInlineButtons14.insert(inlineButton94)
chooseInlineButtons14.insert(inlineButton95)
chooseInlineButtons14.insert(inlineButton96)

chooseInlineButtons15 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons15.insert(inlineButton97)
chooseInlineButtons15.insert(inlineButton98)
chooseInlineButtons15.insert(inlineButton99)
chooseInlineButtons15.insert(inlineButton100)
chooseInlineButtons15.insert(inlineButton101)
chooseInlineButtons15.insert(inlineButton102)
chooseInlineButtons15.insert(inlineButton103)

chooseInlineButtons16 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons16.insert(inlineButton104)
chooseInlineButtons16.insert(inlineButton105)
chooseInlineButtons16.insert(inlineButton106)
chooseInlineButtons16.insert(inlineButton107)

chooseInlineButtons17 = InlineKeyboardMarkup(row_width=1)
chooseInlineButtons17.insert(inlineButton108)
chooseInlineButtons17.insert(inlineButton109)
chooseInlineButtons17.insert(inlineButton110)

#Вернуться в главное меню
button9 = KeyboardButton('Вернуться в главное меню')



btnInfo = KeyboardButton('Информация')
btnMoney = KeyboardButton('Курсы валют')

otherMenu = ReplyKeyboardMarkup(resize_keyboard=True).add(btnInfo, btnMoney)

