from ast import In
from fileinput import filename
from aiogram.types import MediaGroup, InputFile
import description as text


media1 = MediaGroup()
media1.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M100V_red.jpg', filename='M100Vred.jpg'), text.description1, parse_mode='HTML')
media1.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M100V___________.jpg', filename='M100Vblack.jpg'))
media1.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M100V_gray.jpg', filename='M100Vgray.jpg'))
media1.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M100V_green.jpg', filename='M100Vgreen.jpg'))
media1.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M100V_blue.jpg', filename='M100Vblue.jpg'))

media2 = MediaGroup()
media2.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200V_red.jpg', filename='M200Vred.jpg'), text.description2, parse_mode='HTML')
media2.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200V_black.jpg', filename='M200Vblack.jpg'))
media2.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200V_gray.jpg', filename='M200Vgray.jpg'))
media2.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200V_green.jpg', filename='M200Vgreen.jpg'))
media2.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200V_blue.jpg', filename='M200Vblue.jpg'))

media3 = MediaGroup()
media3.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200S_red.jpg', filename='M200Sred.jpg'), text.description3, parse_mode='HTML')
media3.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_black1.jpg', filename='M200Sblack.jpg'))
media3.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200S_gray.jpg', filename='M200Sgray.jpg'))
media3.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_green3.jpg', filename='M200Sgreen.jpg'))
media3.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_blue3.jpg', filename='M200Sblue.jpg'))

media4 = MediaGroup()
media4.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_red.jpg', filename='M300Sred.jpg'), text.description4, parse_mode='HTML')
media4.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_black.jpg', filename='M300Sblack.jpg'))
media4.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_gray.jpg', filename='M300Sgray.jpg'))
media4.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_green.jpg', filename='M300Sgreen.jpg'))
media4.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_blue.jpg', filename='M300Sblue.jpg'))

media5 = MediaGroup()
media5.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300SH_red.jpg', filename='M300SHred.jpg'), text.description5, parse_mode='HTML')
media5.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300SH_black.jpg', filename='M300SHblack.jpg'))
media5.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300SH_gray.jpg', filename='M300SHgray.jpg'))
media5.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300SH_green.jpg', filename='M300SHgreen.jpg'))
media5.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300SH_blue.jpg', filename='M300SHblue.jpg'))

media6 = MediaGroup()
media6.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_red.jpg', filename='M400Sred.jpg'), text.description6, parse_mode='HTML')
media6.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_black.jpg', filename='M400Sblack.jpg'))
media6.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_gray.jpg', filename='M400Sgray.jpg'))
media6.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_green.jpg', filename='M400Sgreen.jpg'))
media6.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_blue.jpg', filename='M400Sblue.jpg'))

media7 = MediaGroup()
media7.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400SH_Red.jpg', filename='M400SHred.jpg'), text.description7, parse_mode='HTML')
media7.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400SH_Black.jpg', filename='M400SHblack.jpg'))
media7.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400SH_Gray.jpg', filename='M400SHgray.jpg'))
media7.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400SH_Green.jpg', filename='M400SHgreen.jpg'))
media7.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400SH_Blue.jpg', filename='M400SHblue.jpg'))

media8 = MediaGroup()
media8.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Red.jpg', filename='M500Sred.jpg'), text.description8, parse_mode='HTML')
media8.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Black.jpg', filename='M500Sblack.jpg'))
media8.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Gray.jpg', filename='M500Sgray.jpg'))
media8.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Green.jpg', filename='M500Sgreen.jpg'))
media8.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Blue.jpg', filename='M500Sblue.jpg'))

media9 = MediaGroup()
media9.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Red.jpg', filename='M600Sred.jpg'), text.description9, parse_mode='HTML')
media9.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Black.jpg', filename='M600Sblack.jpg'))
media9.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Gray.jpg', filename='M600Sgray.jpg'))
media9.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Green.jpg', filename='M600Sgreen'))
media9.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Blue.jpg', filename='M600Sblue.jpg'))

media10 = MediaGroup()
media10.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Red.jpg', filename='M600Nred.jpg'), text.description10, parse_mode='HTML')
media10.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Black.jpg', filename='M600Nblack.jpg'))
media10.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Gray.jpg', filename='M600Ngray.jpg'))
media10.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Green.jpg', filename='M600Ngreen.jpg'))
media10.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M600S_Blue.jpg', filename='M600Nblue.jpg'))

media11 = MediaGroup()
media11.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_red.jpg', filename='N300Sred.jpg'), text.description11, parse_mode='HTML')
media11.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_black.jpg', filename='N300Sblack.jpg'))
media11.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_gray.jpg', filename='N300Sgray.jpg'))
media11.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_green.jpg', filename='N300Sgreen.jpg'))
media11.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M300S_blue.jpg', filename='N300Sblue.jpg'))

media12 = MediaGroup()
media12.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200S_red.jpg', filename='N200Sred.jpg'), text.description12, parse_mode='HTML')
media12.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_black1.jpg', filename='N200black.jpg'))
media12.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M200S_gray.jpg', filename='N200Sgray.jpg'))
media12.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_green3.jpg', filename='N200Sgreen.jpg'))
media12.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/full_M200S_blue3.jpg', filename='N200Sblue.jpg'))

media13 = MediaGroup()
media13.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_red.jpg', filename='N400Sred.jpg'), text.description13, parse_mode='HTML')
media13.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_black.jpg', filename='N400Sblack.jpg'))
media13.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_gray.jpg', filename='N400Sgray.jpg'))
media13.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_green.jpg', filename='N400Sgreen.jpg'))
media13.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M400S_blue.jpg', filename='N400Sblue.jpg'))

media14 = MediaGroup()
media14.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Red.jpg', filename='N500Sred.jpg'), text.description14, parse_mode='HTML')
media14.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Black.jpg', filename='N500Sblack.jpg'))
media14.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Gray.jpg', filename='N500Sgray.jpg'))
media14.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Green.jpg', filename='N500Sgreen.jpg'))
media14.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/M500S_Blue.jpg', filename='N500Sblue.jpg'))

media15 = MediaGroup()
media15.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/200red.jpg', filename='M200SFred.jpg'), text.description15, parse_mode='HTML')
media15.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/200black.jpg', filename='M200SFblack.jpg'))
media15.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/200gray.jpg', filename='M200SFgray.jpg'))
media15.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/200green.jpg', filename='M200SFgreen.jpg'))
media15.attach_photo(InputFile.from_url('https://jukamarket.ua/components/com_jshopping/files/img_products/200green.jpg', filename='M200SFblue.jpg'))